### PR TITLE
Don't pop plots from metadata

### PR DESCRIPTION
**Pull request by jsignell**
This fixes bug where no plots were showing up in the GUI

### CODE REVIEW

**Comment by martindurant** [comment]
Perhaps needs a change to the test which specifically looks at the output of the description panel?

**Comment by martindurant** [comment]
I notice that this is still installing ipywidgets: https://travis-ci.org/intake/intake/jobs/525040505#L675

**Comment by martindurant** [comment]
I think it's because of test_requirements.txt

**Comment by jsignell** [comment]
Isn't ipywidgets still required for tqdm?

**Comment by martindurant** [comment]
Also (sorry), can you update docs/source/api_user.rst to swap out `intake.gui.DataBrowser`? It occurs in the file twice.

**Comment by martindurant** [comment]
> Isn't ipywidgets still required for tqdm?

Even there it ought to be optional, and our tests don't depend on it.

**Comment by martindurant** [comment]
That could have been skip-ci :)
Merging this now.

**Pull request merged**
