### PR TITLE
Aws profile doc

### PR DESCRIPTION
**Pull request by brentonmallen1**
Added an example to help illustrate how one might implement AWS profiles in a catalog definition.

### CODE REVIEW

**Comment by martindurant** [comment]
Sure! Do you think there's scope here to write more generally that there are *many* possible options, that are documented at the various backends and the APIs they talk to?

**Comment by brentonmallen1** [comment]
I'm not exactly sure what you're asking for, do you mind elaborating a little please?

**Comment by martindurant** [comment]
I mean that `profile=` is just one of many possible arguments, and which arguments you can pass depends on the backend. So, as well as giving the one specific example, it'd be nice to point out where to find out more information (e.g., the s3fs/botocore docs, and the gcsfs docs).

**Comment by brentonmallen1** [comment]
sure, I can take a stab at that.

**Comment by martindurant** [comment]
Are you still thinking to add to this?

**Comment by martindurant** [comment]
ping @brentonmallen1

**Comment by brentonmallen1** [comment]
Sorry, life's kinda gotten in the way a bit the past few months.  I am intending to contribute to this as soon as I am able.

**Pull request merged**
