### PR TITLE
Fix get_dir() using fsspec

### PR DESCRIPTION
**Pull request by kadykov**
This is another solution for #739, and it works better than #768.
However, it breaks catalogs created in memory, like in `test_fsspec_integration`

### CODE REVIEW

**Comment by martindurant** [comment]
> it breaks catalogs created in memory

Can you be more specific on what breaks?

**Comment by martindurant** [comment]
> Is it the expected behaviour of _parent()?

Yes, I think it is: fsspec filesystems return file strings within their own understanding of the storage backend, so normally without the protocol attached. `fs.unstrip_protocol` exists to make the full FS-independent path. 

The following code in `fsspec.generic.GenericFileSystem` might be a good way to provide a concrete space for this kind of thing.
```diff
--- a/fsspec/generic.py
+++ b/fsspec/generic.py
@@ -171,6 +171,10 @@ class GenericFileSystem(AsyncFileSystem):
         self.method = default_method
         super().__init__(**kwargs)

+    def _parent(self, path):
+        fs = _resolve_fs(path, self.method)
+        return fs.unstrip_protocol(fs._parent(path))
+
```

**Comment by martindurant** [comment]
Or perhaps like this? I feel like we've written this a few times and now come to anything satisfactory:
```
def abs_parent(path):
    fs, _ = fsspec.core.url_to_fs(path)
    return fs.unstrip_protocol(fs._parent(path))
```

**Comment by kadykov** [comment]
It seems that the solution with `UPath` #773 works better, therefore it is preferable to use it instead.

**Pull request closed without merging**
