### PR TITLE
double dash llama-server kwargs

### PR DESCRIPTION
**Pull request by AlbertDeFusco**

### CODE REVIEW

**Comment by martindurant** [comment]
There are both "-" (for common ones) and "--" arguments - is there any way to tell the difference?

**Comment by AlbertDeFusco** [comment]
I don't have a way to distinguish them. I will add a note in the docs that long-form names are supported as kwargs. I'll check the llama-server help one more time to see if some are single-dash only.

**Comment by martindurant** [comment]
We could maybe maintain an explicit list of short forms to check for, without promising to match all possible future single dash args.

**Comment by AlbertDeFusco** [comment]
That's a good plan.

**Comment by martindurant** [comment]
I'll merge this anyway now, so that you can make a demo :)

**Pull request merged**
