### PR TITLE
auth=None for base Catalog; remove old usage of intake.Catalog

### LINKED ISSUE #542: Regression in opening Catalog from a URL
With intake>=0.5.5, this warns and returns an empty catalog:

```python
>>> import intake
>>> cat_url = 'https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/master.yaml'
>>> cat = intake.Catalog(cat_url)
 UserWarning: deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog
 If you want to open a generic URL, you should use intake.open_catalog
  warnings.warn('deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog\n '
>>> list(cat)
[]
```

With 0.5.4 it returns the expected result

```
>>> list(cat)
['ocean', 'atmosphere', 'climate', 'hydro']
```

### LINKED ISSUE #543: 'auth' attribute and __init__ parameter removed from Catalog
@martindurant Can you comment on the intent behind removing the `auth` attribute and `__init__` parameter from `Catalog`?

https://github.com/intake/intake/commit/bf5fb33d87914e004b29c792791ce208aee78313#diff-4e371ca3c37982987024b768df161ca8c8da696ff4a3459035c122e6cfb9bd15L52-L104

That backward-compatible change broke databroker in several places where we access it and pass it through to new instances, as in for example:

https://github.com/bluesky/databroker/blob/41700e7f04f5dcbd88eec17d4f21ab2a4e2b3c57/databroker/_drivers/mongo_normalized.py#L345

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #543 
Fixes #542 

@danielballan : how hard would it be to add some bluesky tests to a separate CI build? That seems like a good guard against regressions.

### CODE REVIEW

**Comment by martindurant** [comment]
PS: accepting help to transfer tests to githubActions...

**Comment by martindurant** [comment]
@danielballan : I put in the Catalog() change here, to see how it feels. We can split the PR in two, to put in the original auth=None thing separately.

**Comment by danielballan** [comment]
I took the liberty of rewording the error message. I verified that the `databroker` test suite passes against this branch locally.

Yes, let's add a separate CI build (with allowed failures) for databroker. We might as well wait until after the move to GH Actions though.

**Review by danielballan — APPROVED** [review]
Merge at will once CI passes.

**Comment by martindurant** [comment]
> We might as well wait until after the move to GH Actions though.

I am not putting a timeline on that!

**Comment by danielballan** [comment]
I volunteer to move `intake/intake` at the same time I move `bluesky/*`. The others can stay on Travis-CI until we have automation, I think.

**Pull request merged**
