### PR TITLE
Cache enhancement

### LINKED ISSUE #653: Error with cache when running in jupyterlab
More description is given in this [notebook example](https://gist.github.com/Hoxbro/ec14fc9e746c4bc1e24068559d809aba).

### PR DESCRIPTION
**Pull request by Hoxbro**
Fixes #653

### CODE REVIEW

**Comment by michaelaye** [comment]
Ipywidgets is a missing requirement for tqdm though, I don’t think that check should be in intake.

**Comment by martindurant** [comment]
> Ipywidgets is a missing requirement for tqdm though

It's more subtle than that: tqdm works in the terminal and doesn't need ipywidgets, but when in a notebook, it tries to use it. At least, I think so.

**Comment by martindurant** [comment]
I think this is good for fixing the two issues

**Comment by Hoxbro** [comment]
I agree with @martindurant. 

I see `ipywidgets` as an optional dependency for `tqdm` and can be run without it. When https://github.com/tqdm/tqdm/pull/1218 is merged it will also automatic run the `std.tqdm` version instead of the `notebook.tqdm`.

**Comment by michaelaye** [comment]
Sure but I’m confused why intake isn’t leaving the decision if to use a progress bar or not and which one to tqdm? intake shouldn’t have to manage anything about progress bars.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by martindurant** [comment]
I agree with you, @michaelaye , but this workaround can keep up going for now. If it is fixed upstream, we can always remove it.

**Pull request merged**
