### PR TITLE
MNT: clean up remaining leakage of CatalogEntry to public API

### PR DESCRIPTION
**Pull request by tacaswell**
We found another place Entry objects were leaking out to the user via `cat.items()`.  This PR makes `cat.items()` consistent with item and attribute access by returning `DataSource` objects and deals with the internal fallout.

Added a test.

### CODE REVIEW

**Comment by tacaswell** [comment]
I'm not sure what is going on with the 3.6 build, I don't see those failures locally.

**Comment by martindurant** [comment]
So the argument is, if cat[k] -> source, then cat.items() -> iter over sources. I get that.
Should we also have .values() too, then, to fill out the dict namespace?

I am interested, what broke for you?

**Comment by martindurant** [comment]
@tacaswell , would you like me to finish this PR off?

**Comment by tacaswell** [comment]
I am not likely to be able to get to this in the next few days, I am :100: :+1: on you taking over this PR if you want.

It was one of our databroker extensions that was doing `cat.items()`, trying to treat the value as a `DateSource` and failing with attribute error because `Entry` no longer does the attribute fallback.

**Comment by tacaswell** [comment]
Thank you for finishing this @martindurant 8

**Pull request merged**
