### PR TITLE
don't check meta when merging dataframes

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by CJ-Wright** [comment]
This depends on https://github.com/dask/dask/pull/5436

**Comment by CJ-Wright** [comment]
@intake-dev ready for review!

**Comment by martindurant** [comment]
Can you think of any case in which verifying is useful, i.e., should be an option for the user, with a default to not verify?
Should this wait for Dask release?

**Comment by CJ-Wright** [comment]
It might make sense to define verify on a source by source basis, since some dataframes may want verification and some might not. A user override would also be good.

Any idea when the next Dask release will be?

**Comment by martindurant** [comment]
> Any idea when the next Dask release will be?

Not as such, but minor releases often come every fortnight or so, depending on activity. It would be OK to merge here so long as we don't release before they do or - perhaps this is the right thing to do - explicitly check the Dask version to decide whether to use the kwarg or not.

**Comment by CJ-Wright** [comment]
Would an `inspect` of the `from_delayed` signature be too heavy?

**Comment by martindurant** [comment]
I would do `if loose_version(dask.__version__) <= loose_version("..."): no kwarg`

**Comment by CJ-Wright** [comment]
Are there tests for remote catalogs? Can I add a test for this?

**Comment by martindurant** [comment]
Sure - they are under intake/catalog/tests/test_remote_integration, and some more specific tests of the server in intake/cli/server/tests

**Comment by CJ-Wright** [comment]
Would you accept this without a test?

**Comment by martindurant** [comment]
The effect of not using the flag is to create more work, but the same result? Then yes - but I do think the Dask version check should be there, so that updating Intake does not necessarily require latest Dask (even though, in practice, most will be on latest).

**Comment by martindurant** [comment]
Ah, you already did this. Assuming you can confirm that what I say above is correct, I'll merge.

**Comment by CJ-Wright** [comment]
Yes, although there are some corner cases where setting the flag to True will cause errors, since the metadata across the dataframe chunks are not the same. If we put the flag into the sources themselves this should work out, since the source should know if the dataframe metadata is consistent.

**Comment by martindurant** [comment]
OK .Since this is remote, the schema should be always consistent. Merging this now.

**Comment by CJ-Wright** [comment]
Thank you very much!

**Pull request merged**
