### PR TITLE
Precise 'int' type in 'zarr' test

### PR DESCRIPTION
**Pull request by kadykov**
This PR fixes falling 'zarr' test

### CODE REVIEW

**Comment by martindurant** [comment]
This is due to a new version of numpy?
```
assert np.array([1]).dtype == "int"
```

I am fine to merge this, but it confuses me!

**Comment by kadykov** [comment]
I have this output for this test:
I don't know. I agree, it is a bit weird.
```python
intake/source/tests/test_npy.py::test_zarr_minimal failed: def test_zarr_minimal():
        pytest.importorskip("zarr")
        cat = intake.open_catalog(posixpath.join(here, "sources.yaml"))
        s = cat.zarr1()
        assert s.container == "ndarray"
        assert s.read().tolist() == [73, 98, 46, 38, 20, 12, 31, 8, 89, 72]
        assert s.npartitions == 1
>       assert s.dtype == "int"
E       AssertionError: assert dtype('int64') == 'int'
E        +  where dtype('int64') = sources:\n  zarr1:\n    args:\n      urlpath: c:/Users/kadykov/Documents/prog/git_repos/intake/intake/source/tests//data....ZarrArraySource\n    metadata:\n      catalog_dir: c:/Users/kadykov/Documents/prog/git_repos/intake/intake/source/tests/\n.dtype

intake\source\tests\test_npy.py:86: AssertionError
```
OS Windows 10
python 3.8.17
numpy 1.24.4
pytest 7.4.1

**Comment by martindurant** [comment]
Perhaps "int64" would have worked, or 's.dtype.kind == "i"`... Anyway, this is fine now.

**Comment by kadykov** [comment]
Yes, both of these options also work

**Pull request merged**
