### PR TITLE
Fix remote ndarray chunks

### PR DESCRIPTION
**Pull request by jmosbacher**
This addresses issue #449 .

### CODE REVIEW

**Comment by martindurant** [comment]
Would be nice to have a test that demonstrates the problem, and that it is now solved - presumably based on however you found this!

**Comment by jmosbacher** [comment]
Funny, I was just thinking I should have done that. Ill add it to the PR as soon as I can (a bit busy lately).

**Comment by martindurant** [comment]
ping here

**Comment by jmosbacher** [comment]
Sorry, I have been super busy at work lately and havent had any time to write a test for this. Been pushing it off since i cant imagine many people suffering from this tiny bug but will definitely get around to it at some point. I need to build a test that includes a custom data source that doesnt send any "chunks" field in the schema and then set up a server etc., from what i saw in existing tests it should be pretty straight forward but will take some tinkering on my part (ie time).

**Comment by martindurant** [comment]
This issue appears to have dropped into a dark hole :|

**Pull request closed without merging**
