### PR TITLE
Use yaml safe-load everywhere

### LINKED ISSUE #295: Quickstart "unsafe" warning
I just tried running the Intake QuickStart, and it throws a warning that, while isn't really anything to worry about, includes the words `default Loader is unsafe` which new users might find concerning:
 ```python
import intake
ds = intake.open_csv('states_*.csv')
print(ds)
```
produces the warning:
```
/opt/conda/lib/python3.6/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/opt/conda/lib/python3.6/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
```

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #295 and errors with pyyaml 5.1

### CODE REVIEW

**Comment by dotlambda** [comment]
When can we expect a release with this fix? It prevents me from upgrading to PyYAML 5.1.

**Comment by martindurant** [comment]
Good point. I'll do it when I am back home, so after Monday.

**Comment by martindurant** [comment]
https://github.com/conda-forge/intake-feedstock/pull/8

**Comment by dotlambda** [comment]
Thanks a lot!

**Pull request merged**
