### PR TITLE
Catalog discovery with entrypoints

### PR DESCRIPTION
**Pull request by gwbischof**
Fixes https://github.com/intake/intake/issues/404

@danielballan worked on this with me.

### CODE REVIEW

**Comment by martindurant** [comment]
@gwbischof , let us know if you need help here

**Comment by gwbischof** [comment]
@martindurant thanks, any feedback so far? I want to think more about nesting vs flattening the merged catalogs before I change it from a draft PR. I'll add some updates to the docs too.

**Comment by martindurant** [comment]
Sorry, I haven't had the chance yet. I intend to come back to it! I wonder what you think about whether all the potential catalogs should be merged into the top-level intake.cat or not...

**Comment by martindurant** [comment]
@talebzeghmi , @danielballan any thoughts here?

**Comment by talebzeghmi** [comment]
Some documentation on how to register a Catalog with an entry point would be helpful.  This would allow us to register non `YAMLFileCatalog` to the global Intake catalog.

**Comment by danielballan** [comment]
@martindurant I think the behavior proposed in this PR is right: it makes sense to put all the sources listed in any YAMLs on the search path or any entrypoints at top level. This is how intake catalog discovery works currently (minus the entrypoints, of course).

I admit that initially I was against the flattening, but now I think it makes sense. How the package was distributed is an implementation detail. That is, the name shouldn't change if it comes from a YAML file vs a package. We have been trying this out in databroker 1.0.0beta, and it the usage seems nice.

**Comment by danielballan** [comment]
I rebased on the `master` and got the tests passing (locally, at least, TBD if Travis-CI agrees). Are we ready to move forward with this?

**Comment by danielballan** [comment]
Test failures are related to

```
AttributeError: 'DataFrame' object has no attribute 'to_msgpack'
```

caused by pandas choosing to [remove msgpack support](https://pandas.pydata.org/pandas-docs/version/1.0.0/user_guide/io.html?highlight=to_msgpack#msgpack) in order to guide users toward Arrow.

**Comment by martindurant** [comment]
Please merge from master, this should be good to go.

**Comment by danielballan** [comment]
Rebased, CI passes as expected. Thanks for the nudge and the :+1:, @martindurant. Nice to have this in!

**Comment by martindurant** [comment]
Hurray, thank you everyone

**Pull request merged**
