### PR TITLE
fixed typo in quickstart

### PR DESCRIPTION
**Pull request by rsignell-usgs**
[skip ci]

### CODE REVIEW

**Comment by martindurant** [comment]
The failure here is likely also due to the new pyyaml.

**Comment by martindurant** [comment]
Merging from master should fix this. For future reference, doc-only PRs can have `[skip ci]` in the commit messages to avoid waiting on Travis.

**Comment by rsignell-usgs** [comment]
Cool! I did not know about that. Thanks for grabbing the teachable moment!

**Comment by martindurant** [comment]
Yeah, sorry, I should have merged this before the other PR, so that the build shows up as green. 
Would you mind merging from intake/master?

**Comment by martindurant** [comment]
Thanks!

**Pull request merged**
