### PR TITLE
Use styles

### PR DESCRIPTION
**Pull request by martindurant**
ref #397

### CODE REVIEW

**Comment by martindurant** [comment]
@talebzeghmi, @andersy005 @jukent, @danielballan , I have started your respective sections and left plenty of space :)

**Comment by andersy005** [comment]
@martindurant, do you mind if I push some changes to your branch?

**Comment by martindurant** [comment]
That's fine - i need to give permissions? Alternatively, you can post text as comments.

On August 9, 2019 8:17:30 PM EDT, Anderson Banihirwe <notifications@github.com> wrote:
>@martindurant, do you mind if I push some changes to your branch?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/intake/intake/pull/402#issuecomment-520101014

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andersy005** [comment]
@martindurant, 

It looks like I needed permissions to push to your branch. Below is the text:


```rst
National Center for Atmospheric Research
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

NCAR has developed `intake-esm`_, a mechanism for creating file-based Intake catalogs
for climate data from project efforts such as the `Coupled Model Intercomparison Project (CMIP)`_ 
and the `Community Earth System Model (CESM) Large Ensemble Project`_.  
These projects produce a huge of amount climate data persisted on tape, disk storage components 
across multiple (in the order of 300,000) netCDF files. Finding, investigating, loading these files into data array containers 
such as `xarray` can be a daunting task due to the large number of files a user may be interested in. 
``Intake-esm`` addresses this issue in three steps:

- `Data Curation`_ in form of YAML files. These YAML files provide information about where the data is located, 
  the directory structure, etc. ``intake-esm`` uses these YAML files in conjunction with file name templates 
  to construct a local database. Each row in this database consists of a set of metadata such as ``experiment``, 
  ``modeling realm``, ``frequency`` corresponding to data contained in a netCDF file.

   .. code-block:: python

   >>> col = intake.open_esm_metadatastore(collection_input_definition="GLADE-CMIP5")


- Search and Discovery: once the database is built, `intake-esm` can be used for searching and discovering
  of climate datasets by eliminating the need for the user to know specific locations (file path) of 
  their data set of interest:

   .. code-block:: python

   >>> cat = col.search(variable=['hfls'], frequency='mon',
       ...          modeling_realm='atmos',
       ...          institute=['CCCma', 'CNRM-CERFACS'])

- Access: when the user is satisfied with the results of their query, they can ask ``intake-esm`` 
  to load the actual netCDF files into xarray datasets:

   .. code-block:: python

   >>> dsets = cat.to_xarray(decode_times=True, chunks={'time': 50})

.. _intake-esm: https://github.com/NCAR/intake-esm
.. _Data curation: https://github.com/NCAR/intake-esm-datastore
.. _Coupled Model Intercomparison Project (CMIP): https://www.wcrp-climate.org/wgcm-cmip
.. _Community Earth System Model (CESM) Large Ensemble Project: http://www.cesm.ucar.edu/projects/community-projects/LENS/
```

**Comment by martindurant** [comment]
Thanks, @andersy005

**Comment by martindurant** [comment]
@CJ-Wright , you might have some insight for this page too

**Comment by CJ-Wright** [comment]
I don't have anything for it at the moment, but I will keep it in mind.

**Pull request merged**
