### PR TITLE
Don't attempt to serialise functions in server response

### PR DESCRIPTION
**Pull request by martindurant**
ref: #353

### CODE REVIEW

**Comment by martindurant** [comment]
This is a bit of a hack... I don't think there's any legitimate use for functions to be passed to the client, and the client won't pass them back, but perhaps somehow we should be careful not to accidentally override functions that are defined only server-side.

**Comment by danielballan** [comment]
Ha, the branch name made me laugh. Agreed that this is a bit of hack, but maybe a good last-resort fallback even if we come up with something more graceful higher up.

The same approach would need to be taken in `ServerInfoHandler.get` as well.

**Comment by danielballan** [comment]
I opened a PR against this PR https://github.com/martindurant/intake/pull/1

That _seems_ to have resolved this issue for the intake-bluesky tests, but solving it has exposed a second breakage that seems not related to serialization. Investigating.

**Comment by danielballan** [comment]
In fact, the "second breakage" was just a hard-to-trace side effect of double nesting the response [here](https://github.com/intake/intake/pull/354/commits/09dcb7c6d39477537af72566dbca0a6be605f24c#diff-92c1a6d6dd4df7c92054d816cd1d4475R211) and [here](https://github.com/intake/intake/pull/354/commits/09dcb7c6d39477537af72566dbca0a6be605f24c#diff-92c1a6d6dd4df7c92054d816cd1d4475R223) in 09dcb7c. With https://github.com/martindurant/intake/pull/2, the intake-bluesky tests pass.

Thanks for indulging a bit of a hack to fix us. :-) I have set up a nightly Travis-CI Cron Job running intake-bluesky against intake `master` so that intake-bluesky should act as a more prompt "canary" in future.

**Comment by martindurant** [comment]
Good idea on the cron. I was thinking of doing that against other intake repos too.

**Comment by martindurant** [comment]
CI passed, but didn't update here for some reason - sorry to keep you waiting.

**Comment by danielballan** [comment]
Not at all, thanks again for jumping on this!

**Pull request merged**
